#
# Corretto 17 image build workflow for releases.
#
# Every time something is pushed to the "releases" branch,
# build multi-architecture container images based on
# Amazon Corretto 17. Push these images to Docker Hub.
#
# These images will be based on a fixed release of the
# MDA, rather than the current snapshot. Re-running the
# workflow manually can be used to update the underlying
# Corretto image.
#
name: Build Corretto release images

on:
  push:
    branches:
      - releases
  workflow_dispatch:

jobs:

  build-release-images:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Inspect builder
      run: |
        echo "Name:      ${{ steps.buildx.outputs.name }}"
        echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
        echo "Status:    ${{ steps.buildx.outputs.status }}"
        echo "Flags:     ${{ steps.buildx.outputs.flags }}"
        echo "Platforms: ${{ steps.buildx.outputs.platforms }}"

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Corretto 17 multi-architecture image
      run: |
        docker buildx build --platform=linux/amd64,linux/arm64 \
          --push \
          --tag ${{ secrets.DOCKER_USERNAME }}/shibboleth-mda-docker:0.10.0 \
          amazoncorretto-17
